
export const FETCH_DOCUMENT_LIST = 'FETCH_DOCUMENT_LIST';
export const SET_DOCUMENT_LIST = 'SET_DOCUMENT_LIST';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';
